# Generated by Django 4.2.4 on 2023-08-20 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bids_categories_comments_watchlist_listings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='category',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='listings',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='auctions.categories'),
        ),
    ]
